In [8]:
import datetime

import numpy as np
import spiceypy

In [11]:
kernels = [
    '../kernels/spk/de432s.bsp',
    '../kernels/spk/codes_300ast_20100725.bsp',
    '../kernels/misc/codes_300ast_20100725.tf',
    '../kernels/lsk/naif0012.tls',
    '../kernels/pck/gm_de431.tpc'
]

for kernel in kernels:
    spiceypy.furnsh(kernel)

print("Total Kernels Loaded:", spiceypy.ktotal("ALL"))


datetime_utc = datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%S")

datetime_et = spiceypy.utc2et(datetime_utc)

Total Kernels Loaded: 9


In [12]:
mat = spiceypy.sxform(instring="ECLIPJ2000_DE405",
                      tostring="ECLIPJ2000",
                      et=datetime_et)

for mat_row in mat:
    print(np.round(mat_row, 2))

[1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0.]
[ 0. -0.  1.  0.  0.  0.]
[0. 0. 0. 1. 0. 0.]
[0. 0. 0. 0. 1. 0.]
[ 0.  0.  0.  0. -0.  1.]
